package by.htp.ts.command;

public enum CommandName {

	AUTHORIZATION, 
	REGISTRATION, 
	CHANGE_LOCALE, 
	SIGN_OUT, 
	CREATE_TEST, 
	ADD_QUESTION, 
	CLOSE_ADD_QUESTION,
	UPDATE_QUESTION,
	VIEW_LIST_TEST,
	VIEW_LIST_TEST_FOR_USER,
	VIEW_LIST_TESTS_RESULTS,
	RUN_TEST,
	RUN_TEST_NEXT_QUESTION,
	FINISH_RUN_TEST,
	ASSIGN_TEST,
	DELETE_TEST,
	
	GO_TO_SIGN_IN_PAGE, 
	GO_TO_MAIN_PAGE, 
	GO_TO_ERROR_PAGE,
	GO_TO_REGISTRATION_PAGE, 
	GO_TO_CREATE_TEST_PAGE, 
	GO_TO_ADD_QUESTION_PAGE,
	GO_TO_LIST_QUESTION_BY_TEST_PAGE,
	GO_TO_ASSIGN_TEST_PAGE
	
}
